networks:
  verger.net:
    driver: bridge
services:
  web:
    image: canals/php:latest
    restart: always
    ports:
      - "11000:80"
    volumes:
      - ./app/:/var/www/
    networks:
      - verger.net
    depends_on:
      - sql


  sql:
    image: 'postgres:latest'
    restart: always
    env_file: ./base.env
    ports:
      - "11003:5432"
    networks:
      - verger.net
    container_name: bdd
    volumes:
      - ./sql:/var/sql


  adminer:
    image: adminer:latest
    restart: always
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '11008:8080'
    networks:
      - verger.net
